// Downloads the rendering stack + a Live2D sample model into local folders so
// Kodama runs fully offline (no CDN at runtime). These assets are .gitignored:
// Cubism Core and the official sample models are proprietary / redistribution-
// restricted, so we fetch them on setup rather than commit them.
//
// Usage:
//   pnpm run setup            # default model (wanko)
//   pnpm run setup rice       # pick a model: wanko | rice | mark | haru
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const VENDOR = join(ROOT, 'src/renderer/vendor')
const MODELS_DIR = join(ROOT, 'src/renderer/models')

const LIBS = [
  ['https://cdn.jsdelivr.net/npm/pixi.js@6.5.10/dist/browser/pixi.min.js', 'pixi.min.js'],
  ['https://cdn.jsdelivr.net/npm/pixi-live2d-display@0.4.0/dist/cubism4.min.js', 'cubism4.min.js'],
  // Cubism Core is proprietary and cannot be served from npm — official CDN only.
  ['https://cubism.live2d.com/sdk-web/cubismcore/live2dcubismcore.min.js', 'live2dcubismcore.min.js'],
]

// All Cubism 4, free Live2D official samples (small-team commercial use OK, keep
// the attribution in the About page, do not redistribute the raw model files).
const CC = 'https://cdn.jsdelivr.net/gh/Live2D/CubismWebSamples@develop/Samples/Resources'
const MODEL_REGISTRY = {
  wanko: { base: `${CC}/Wanko`, entry: 'Wanko.model3.json' }, // 圆头小狗
  rice: { base: `${CC}/Rice`, entry: 'Rice.model3.json' }, // 圆胖饭团
  mark: { base: `${CC}/Mark`, entry: 'Mark.model3.json' }, // 大圆脸吉祥物
  haru: {
    base: 'https://cdn.jsdelivr.net/gh/guansss/pixi-live2d-display@master/test/assets/haru',
    entry: 'haru_greeter_t03.model3.json',
  },
}

const MODEL_KEY = (process.argv[2] || process.env.KODAMA_MODEL || 'wanko').toLowerCase()
const model = MODEL_REGISTRY[MODEL_KEY]
if (!model) {
  console.error(`unknown model "${MODEL_KEY}". choices: ${Object.keys(MODEL_REGISTRY).join(', ')}`)
  process.exit(1)
}

async function dl(url) {
  const r = await fetch(url)
  if (!r.ok) throw new Error(`${r.status} ${r.statusText} <- ${url}`)
  return Buffer.from(await r.arrayBuffer())
}

async function save(buf, path) {
  await mkdir(dirname(path), { recursive: true })
  await writeFile(path, buf)
}

function collectModelRefs(json) {
  const refs = new Set()
  const fr = json.FileReferences || {}
  for (const key of ['Moc', 'Physics', 'Pose', 'DisplayInfo', 'UserData']) {
    if (fr[key]) refs.add(fr[key])
  }
  for (const t of fr.Textures || []) refs.add(t)
  for (const exp of fr.Expressions || []) if (exp.File) refs.add(exp.File)
  for (const group of Object.values(fr.Motions || {})) {
    for (const m of group) if (m.File) refs.add(m.File)
  }
  return [...refs]
}

async function main() {
  for (const [url, name] of LIBS) {
    process.stdout.write(`vendor: ${name} ... `)
    await save(await dl(url), join(VENDOR, name))
    console.log('ok')
  }

  const dir = join(MODELS_DIR, MODEL_KEY)
  process.stdout.write(`model[${MODEL_KEY}]: ${model.entry} ... `)
  const entryBuf = await dl(`${model.base}/${model.entry}`)
  await save(entryBuf, join(dir, model.entry))
  console.log('ok')

  const refs = collectModelRefs(JSON.parse(entryBuf.toString()))
  let failed = 0
  for (const rel of refs) {
    process.stdout.write(`  ${rel} ... `)
    try {
      await save(await dl(`${model.base}/${rel}`), join(dir, rel))
      console.log('ok')
    } catch (e) {
      failed += 1
      console.log(`skip (${e.message.split(' ')[0]})`) // optional files (cdi3/pose) may 404
    }
  }

  // Single source of truth for the renderer (relative to src/renderer/).
  await save(
    Buffer.from(
      `// generated by scripts/setup-assets.mjs — do not edit\nexport const CURRENT_MODEL = './models/${MODEL_KEY}/${model.entry}'\n`,
    ),
    join(MODELS_DIR, 'current-model.js'),
  )

  console.log(
    `\nDone: ${LIBS.length} libs + model "${MODEL_KEY}" (${refs.length - failed}/${refs.length} files; ${failed} optional missing).`,
  )
}

main().catch((e) => {
  console.error('\nsetup failed:', e.message)
  process.exit(1)
})
